kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: consul-3
  annotations:
    volume.beta.kubernetes.io/storage-class: "ebs-standard"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
